language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install: 
  - pip install . pytest mock codecov==1.5.1 behave pexpect==3.3

script:
  - coverage run --source pgcli -m py.test
  - cd tests
  - behave

build_image: drydock/u14pytpls:prod 
